/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.com.fpv.btg;

import co.com.fpv.btg.usecases.fund.IFundUseCaseGateway;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@RequiredArgsConstructor
@SpringBootApplication
public class Application implements CommandLineRunner {
	private final IFundUseCaseGateway fundUseCaseGateway;
	public static void main(String args[]) {
		SpringApplication.run(Application.class, args);
	}

	@Override
	public void run(String... args) throws Exception {
		fundUseCaseGateway.createDefaultFund();
	}
}

